// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_isaacmel.Models;

namespace Mission6_isaacmel.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230214022447_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_isaacmel.Models.MovieForm", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Action/Adventure",
                            DirectorFirstName = "Gary",
                            DirectoryLastName = "Gray",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Italian Job, The",
                            Year = 2003
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Action/Adventure",
                            DirectorFirstName = "Christopher",
                            DirectoryLastName = "Nolan",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Batman Begins",
                            Year = 2005
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Action/Adventure",
                            DirectorFirstName = "Andrew",
                            DirectoryLastName = "Davis",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "The Fugitive",
                            Year = 1993
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
